# -*- coding: utf-8 -*-
"""Lista_ de_Exercicios_04/03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMqp40Pnje9g_FLednktE3l5BFyQJkmn

1. Ler uma lista de 5 números inteiros e mostre cada número
juntamente com a sua posição na lista.
"""

lista = [-7, 2, 20, -4, 5]

i=0

for item in lista:
  print(f'{i}: {item}')
  i+=1

"""2. Ler uma lista de 10 números reais e mostre-os na ordem inversa
que foram lidos.
"""

lista = [7, 2, 20, 4, 5, 12, 15, 17, 22, 92]
lista.reverse()
print(f'{lista}')

"""3. Ler uma lista com 5 idades e exibir a maior e a menor."""

lista = [18, 22, 39, 66, 90]
min(lista)
max(lista)
print(f'{min(lista)}')
print(f'{max(lista)}')

"""4. Inicialize uma lista de 10 números inteiros. Armazene os números
pares em uma lista PAR e os números ímpares em uma lista IMPAR.
Imprima as listas PAR e IMPAR.
"""

numeros = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10]
apenas_pares = [x for x in numeros if x % 2 == 0]
apenas_impares = [y for y in numeros if y % 2 != 0]


print(apenas_pares)
print()
print(apenas_impares)
print()

"""5. Escreva um programa que troque o primeiro com o último
elemento de uma lista qualquer.
"""

Lista = ['Alex' , 'Vinicius' , 'Granja' , 'Rafael' , 'Igor', 'Marcelo']

Lista[0], Lista[-1] = Lista[-1], Lista[0]
print(Lista)

"""6. Qual a saída/resultado da seguinte compreensão de lista?

Você consegue entender e explicar o resultado?
"""

#Para cada interação de 'i', vamos adicionar 'j' ao range 'j' com isso se formam lista de listas e como o 'j' é multiplicado por tres conseguem listas.
 [[i + j * 3 + i for i in range(3)] for j in range(3)]

"""7. Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.

Você deve criar um programa em Python que solicite ao usuário que insira um preço
máximo. Em seguida, o programa deve imprimir os produtos cujo preço seja menor ou
igual ao preço máximo inserido pelo usuário.
"""

preco = float(input("Digite um Valor: "))

produtos = {
'camiseta': (25.00, 10),
'calça': (45.00, 5),
'sapato': (60.00, 3),
'boné': (15.00, 8)
}

for chave in produtos:
  if preco > produtos[chave][0]:
    print(chave)

8. Em uma competição de ginástica, cada atleta recebe votos de
sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica
sendo a média dos votos restantes. Você deve fazer um programa
que receba o nome do ginasta e as notas dos sete jurados
alcançadas pelo atleta em sua apresentação e depois informe a sua
média, conforme a descrição acima informada (retirar o melhor e o
pior salto e depois calcular a média com as notas restantes). As
notas não são informadas em ordem crescente ou decrescente.

atleta = str(input("Nome da Atleta: "))
notas = []
for nt in range(7):
  notas.append(float(input("Digite uma nota: ")))
print(notas)
notas.sort()
notas = notas[1:-1]
media = sum(notas) / len(notas)
print(f"A média da {atleta} é de {media}")

def calcular_media(notas):
    notas.sort()  # Ordena as notas em ordem crescente
    notas = notas[1:-1]  # Remove a melhor e a pior nota
    media = sum(notas) / len(notas)  # Calcula a média das notas restantes
    return media

nome_ginasta = input("Digite o nome do ginasta: ")
notas = []

# Recebe as notas dos jurados
for i in range(7):
    nota = float(input(f"Digite a nota do jurado {i+1}: "))
    notas.append(nota)

media_final = calcular_media(notas)
print(f"A média final do ginasta {nome_ginasta} é: {media_final}")

m =  [1, -3, 5, 8]

last = m[-1]
m[-1] = m[0]
m[0] = last

print(m)

dir(list)

help(print)